### ISSUE TITLE
Add Dust to Ingot Smelting to Kiln and Blast Furnace. (See Documentation)

### ISSUE THREAD

**Issue by jacobwilki01** [asylumdevgroup/Ultimatum-XII#18]
Add in IngotCreation.zs
To the Alloy Kiln: All Level 1 Metals. All Level 2 Metals, except Uranium. Crafting of Bronze, Invar, Constantan, Electrum, and Brass with CoT dusts.
To the Blast Furnace: Uranium. All level 3 metals. All Nether Metals. Smelting of Refined Iron, Redmetal, Manyullyn, Signalum, Lumium, Chrome, Enderium, Tungstensteel, Tungsten, Iridium, and Mithril from CoT dusts.

**Comment by jarodsstuff** [comment]
I'm going to separate this issue into multiple issues for each tier of metal.
