### ISSUE TITLE
AdvancedMortars.zs

### ISSUE THREAD

**Issue by jacobwilki01** [asylumdevgroup/Ultimatum-XII#19]
- [ ] Disable Stone Mortar and Pestle.

- [ ] Add to Configs of Iron Mortar the dust crafting of the light metals. 

- [ ] Add to Configs of Diamond Mortar the dust crafting of light metals and heavy metals.

For Light and Heavy Metals, see Issue #18

**Comment by Kaperios** [comment]
No longer used
